services:
  db:
    image: mongo:6
    restart: always
    volumes:
      - shared-data:/data/db
    networks:
      - login-app

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./Backend:/app
      - /app/node_nodules
    networks:
      - login-app
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - login-app
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - backend


volumes:
  shared-data: {}
networks:
  login-app:
    driver: bridge
