version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL='mongodb+srv://tukamothupi_db_user:2FStjH8gT1rDX0WW@thedeveloper.bkgwozo.mongodb.net/?appName=TheDeveloper'
    depends_on:
      - db

  db:
    image: mongo:6
    restart: always
    volumes:
      - shared-data:/data/db

volumes:
  shared-data: {}
